permalink: /:title

title: Kyrisiss Blog
url: https://zhoubohan.github.io
feed: /atom.xml
author_info: <a href="https://zhoubohan.github.io/">ZhouBohan</a>

paginate: 5
paginate_path: "_posts/blog/page:num"

theme: jekyll-theme-hacker